export { default as AdminLayout } from '../layout/adminLayout'
export { default as Login } from './auth/login'
export { default as Home } from './home'
export { default as Roles } from './managements/roles/roles'
export { default as FormRoles } from './managements/roles/formRoles'
export { default as Services } from './managements/services/services'
export { default as FormService } from './managements/services/formService'
export { default as Register } from './register/register'
export { default as Users } from './managements/users/users'
export { default as FormUsers } from './managements/users/formUsers'
export { default as Permissions } from './managements/permissions/permissions'
export {default as FormPermissions} from './managements/permissions/formPermissions'
export {default as PermissionInGroup} from './managements/permission-in-group/permissionInGroup'